metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
  - module: elasticsearch
    xpack.enabled: true
    period: 10s
    hosts: ${ELASTIC_HOSTS}
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}
    ssl.enabled: true
    ssl.certificate_authorities: "certs/ca/ca.crt"
    ccr.enabled: false

  - module: kibana
    metricsets:
      - stats
    period: 10s
    hosts: ${KIBANA_HOSTS}
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}
    xpack.enabled: true

  - module: logstash
    xpack.enabled: true
    period: 10s
    hosts: ${LOGSTASH_HOSTS}

  - module: docker
    metricsets:
      - container
      - cpu
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

    processors:
      - drop_fields:
          fields:
            - docker.container.labels
            - docker.container.image
            - docker.container.command
            - docker.container.created
            - docker.container.network

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl:
    enabled: true
    certificate: "certs/es01/es01.crt"
    certificate_authorities: "/usr/share/metricbeat/certs/ca/ca.crt"
    key: "certs/es01/es01.key"