# Activer le moteur ModSecurity
SecRuleEngine On

# Logs
SecAuditEngine RelevantOnly
SecAuditLog /var/log/nginx/modsec_audit.log
SecAuditLogParts ABIJDEFHZ

# Accès aux corps de requêtes
SecRequestBodyAccess On
SecResponseBodyAccess Off

# Répertoires temporaires
SecTmpDir /tmp
SecDataDir /tmp

SecAction \
"id:1000001,\
phase:1,\
pass,\
nolog,\
setvar:'tx.allowed_methods=GET HEAD POST PUT PATCH DELETE OPTIONS'"

# Charger CRS
Include /etc/nginx/crs/crs-setup.conf
Include /etc/nginx/crs/rules/*.conf
