input {
    beats {
        port => 5044
    }
}

output {
    elasticsearch {
        index => "%{[@metadata][beat]}-%{[@metadata][version]}"
        user => "${ELASTIC_USER}"
        password => "${ELASTIC_PASSWORD}"
        hosts => ["${ELASTIC_HOSTS}"]
        ssl => true
        cacert => "/usr/share/logstash/config/certs/ca/ca.crt"
        action => "create"
    }
}